[common]
base = /scratch/ek9/jw5893/TurbulentDynamo/Mach0.1IdealSolHighRes
output_dir = /scratch/ek9/jw5893/TurbulentDynamo/Mach0.1IdealSolHighRes
kin_spect = false
mag_spect = false
cur_spect = false
vort_spect = false
kin_plot = true
mag_plot = true
cur_plot = true
vort_plot = false
verbose = 2
lf = 5e-6
uf = 5e-3
stf = 3.0
n = 8
refit = true
noShift = false
showx = false
oname = 

[directories]
i = SplitRoe256, SplitBouchut256, Roe256, HLLD256, HLLC256, BK256_MCut0.4_M0.1, BK256
; i = HLLD256, BK256_MCut0.4_M0.1, BK256
; i = BK256

[args]
fitFile = 
factor = 1.0, 0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001
color = #377eb8, #f781bf, #a65628, #984ea3, #4daf4a, #ff7f00, #e41a1c
label = Split-Roe, Split-Bouchut, USM-Roe, USM-HLLD, USM-HLLC, USM-BK, USM-BK(Cut0.1)
; factor = 1.0, 0.1, 0.01
; color = #377eb8, #4daf4a, #ff7f00
; label = USM-HLLD, USM-BK(MCut0.04), USM-BK(MCut0.01)
; factor = 1.0
; color = #377eb8
; label = BK(MCut0.1)